### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by cookins** [nebarnix/img2gco#5]
hello
im trying to use this web app, its cool, i think, but i got in every picture black background - i need just black letters, but it makes black background with "white letters".... i tried to invert picture, but its still doing same thing... can you explain what i doing wrong? thanks!

**Comment by nebarnix** [comment]
Send me a screenshot of the settings you are plugging in and an image
please!

**Comment by cookins** [comment]
Here is screen of settings, printed image and how it got on timber. A you can see it have black background with half black letters, that is barely seen. Same if I invert picture. That's background, while it's transparent in that image. Hope you can tell me why this happening. Thanks.
![IMG_20201223_205527_334.png](https://user-images.githubusercontent.com/7893051/103028885-4c595800-4561-11eb-8228-4221913ae84a.png)
![IMG_20201223_202750_375.jpg](https://user-images.githubusercontent.com/7893051/103028901-52e7cf80-4561-11eb-90cc-dd7cb682d7af.jpg)
![1608749852818.jpg](https://user-images.githubusercontent.com/7893051/103029008-8cb8d600-4561-11eb-84e6-d6176987c5c0.jpg)

**Comment by nebarnix** [comment]
Is 10 power enough to not mark? What if you set min AND max to 10? It
should not laser at all, if it does, 10 is too high of power? Else, maybe
your laser driver isn't turning off ?

**Comment by cookins** [comment]
I see. I thought "Off" is for white... Yes. Even at power 001 it burn a bit. Then I will set 0 also for "min" then. Same as "off". Let me engrave new one with new options.

**Comment by cookins** [comment]
I tried again with new options. Sadly right same. And yes, when 0 - laser shut downs.
![1608752478334.jpg](https://user-images.githubusercontent.com/7893051/103032033-bc6adc80-4567-11eb-85f7-63df7fe89aed.jpg)
![IMG_20201223_214331_303.png](https://user-images.githubusercontent.com/7893051/103032102-e7edc700-4567-11eb-816f-31689785c9da.png)

**Comment by cookins** [comment]
I think I know reason...
Seems web app see transparency as black... that's reason.

**Comment by nebarnix** [comment]
Sweet!!! 🥰
